config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    resources :foods
    resources :recipes do
      collection do
        get 'public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
        get 'my_recipes', to: 'recipes#my_recipes', as: 'my_recipes'
      end

      member do
        get 'shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'
      end

      resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  root 'foods#index'

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  get '/my_recipes', to: 'recipes#my_recipes', as: 'my_recipes'
  get '/shopping_list', to: 'shopping_list#general', as: 'general_shopping_list'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :manage, Food, user_id: user.id
      can :manage, Recipe, user_id: user.id
      can :manage, RecipeFood, recipe: { user_id: user.id }
      can :read, :all
    end
  end
end

app/models/application_record.rb
# application_record.rb

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, inverse_of: :food, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, inverse_of: :recipe, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :is_public, inclusion: { in: [true, false] }
  validates :name, :preparation_time, :cooking_time, presence: true
  validates :preparation_time, :cooking_time, numericality: { only_integer: true }

  def recipes_total_price
    recipe_foods.sum { |rf| rf.food.price * rf.quantity }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, foreign_key: 'food_id', inverse_of: :recipe_foods
  belongs_to :recipe, foreign_key: 'recipe_id', inverse_of: :recipe_foods

  validates_presence_of :quantity

  before_save :calculate_value

  def calculate_value
    self.value = quantity * food.price
  end
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :recipe_foods, through: :recipes

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_current_user
    @current_user = current_user
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @foods = @user.foods.all
  end

  def show; end

  def new
    @food = Food.build
  end

  def create
    @user = current_user
    @food = @user.foods.build(food_params)
    @food.user_id = @user.id
    if @food.save
      redirect_to foods_path(@user), notice: 'Food was successfully created.'
    else
      render :new, alert: 'Failed to create food.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete food.'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/recipe_foods_controller.rb
# app/controllers/recipe_foods_controller.rb

class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_foods_params)

    if @recipe_food.save
      redirect_to @recipe, notice: 'Ingredient added successfully.'
    else
      render 'recipe_foods/new'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe

    if @recipe_food.destroy
      redirect_to @recipe, notice: 'Ingredient removed successfully.'
    else
      redirect_to @recipe, alert: 'Failed to remove ingredient.'
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe

    if @recipe_food.update(recipe_foods_params)
      redirect_to @recipe, notice: 'Ingredient modified successfully.'
    else
      render 'edit'
    end
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:food_id, :quantity, recipe_foods: %i[food_id quantity])
  end
end

app/controllers/recipes_controller.rb
# app/controllers/recipes_controller.rb

class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(is_public: true)
  end

  def my_recipes
    @recipes = current_user.recipes.includes(:user)
    render 'my_recipes'
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new, alert: 'Failed to create recipe.'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete recipe.'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe was successfully updated.'
    else
      render :edit, alert: 'Failed to update recipe.'
    end
  end

  def shopping_list
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :is_public)
  end
end

app/controllers/shopping_list_controller.rb
# app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!

  def general
    @user = current_user
    @missing_foods = calculate_missing_foods(@user)
    @total_items = @missing_foods.count
    @general_total_price = calculate_total_price(@missing_foods)
  end

  private

  def calculate_missing_foods(user)
    # Find all foods associated with the user
    user_foods = user.foods.to_a

    # Find all foods associated with the user's recipes
    recipe_foods = RecipeFood.joins(:food, :recipe).where(foods: { user_id: user.id })

    # Identify deficit items
    deficit_items = []
    recipe_foods.each do |rf|
      user_food = user_foods.find { |uf| uf == rf.food }
      deficit_quantity = [rf.quantity - user_food.quantity, 0].max
      deficit_items << { food: user_food, deficit_quantity: } if deficit_quantity.positive?
    end

    deficit_items
  end

  def calculate_total_price(missing_foods)
    missing_foods.sum { |item| item[:food].price * item[:deficit_quantity] }
  end
end

app/controllers/users_controller.rb
# controllers/users_controller.rb

class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/foods/index.html.erb
<!-- views/foods/index.html.erb -->

<div class="container p-3">
  
 <h1 class="text-center h1">Foods page</h3>
 <div class="container d-flex justify-content-end pe-5 mb-2">
  <%= button_to "Add Food", new_food_path, method: :get, class: "btn btn-sm btn-outline-secondary"  if @user.id == current_user.id%>
 </div>
 <table class="table table-striped">
 <% if @foods.present? %>
     <thead>
       <tr class="table-active">
         <th class="input title" >Food</th>
         <th class="input title" >Measurement unit</th>
         <th class="input title">Unit price</th>
         <th class="input title">Actions</th>
        </tr>
     </thead>
   <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td class="input"><%= food.name %></td>
        <td class="input"><%= food.measurement_unit %></td>
        <td class="input"><%= food.price %></td>
        <% if food.user_id == current_user.id || @user.admin? %>
        <td class="input">
          <%= button_to "Delete", food_path(food), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>
        <% end %>
      </tr>
       <% end %>
       </tbody>
       <% else %> 
        <p class="text-center display-6 ">No foods found</p>
    <% end %>
</table>
</div>

app/views/foods/new.html.erb
<!-- views/foods/new.html.erb -->

<div class="container w-75">
<h4> Add new food</h4>

<%= form_with model: @food, url: foods_path do |form| %>
  <% if @food.errors.any? %>
  <div>
      <h2><%= pluralize(food.errors.count, "error") %> Food cannot be saved:</h2>
          <ul>
            <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
          </ul>
  </div>
  <% end %>
  <div class="d-flex flex-column">
    <div>
      <%= form.label :name%><br>
      <%= form.text_field :name, class: 'form-control', required: true%>
    </div>
    <div>
      <%= form.label :measurement_unit %><br>
      <%= form.select :measurement_unit, options_for_select(['Pieces', 'Grams', 'kg', 'Dozen','Liters']), { prompt: 'Select a category...' }, class: 'form-control' %>
    </div>
    <div>
      <%= form.label :price%><br>
      <%= form.number_field :price, class: 'form-control', required: true%>
    </div>
    <div>
      <%= form.label :quantity %><br>
      <%= form.number_field :quantity, class: 'form-control', required: true%>
    </div>
    <%=form.submit "Create food", class: "btn btn-outline-success mt-5"%>
  </div>
  </div>
 <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeAppRailsGroupProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>

    <% if user_signed_in? %>
    <div class="container">
    <!-- Navbar with User label, Logout button, and Buttons -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">

      <!-- Buttons -->
      <div class="d-flex gap-4">
  <%= link_to "Foods", foods_path, class: "btn btn-outline mx-2 #{params[:controller] == 'foods' ? 'active' : ''}" %>
  <%= link_to "Public Recipes", recipes_path, class: "btn btn-outline mx-2 #{params[:controller] == 'recipes' && params[:action] == 'index' ? 'active' : ''}" %>
  <%= link_to "My Recipes", my_recipes_path, class: "btn btn-outline mx-2 #{params[:controller] == 'recipes' && params[:action] == 'my_recipes' ? 'active' : ''}" %>
  <%= link_to "General Shopping List", general_shopping_list_path, class: "btn btn-outline mx-2 #{params[:controller] == 'shopping_list' && params[:action] == 'general' ? 'active' : ''}" %>
</div>


      <div class="d-flex gap-4">
        <!-- User label -->
        <p class="navbar-text text-muted mr-3">
          Welcome, <%= @current_user.name %>
        </p>

        <!-- Logout button -->
        <form class="form-inline my-2 mx-2">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-dark" %>
        </form>

      </div>
      
    </nav>
    </div>
  <% end %>

  <div class="container">
    <!-- Notice and Alert messages -->
    <p class="notice text-success ml-5"><%= notice %></p>
    <p class="alert text-danger ml-5"><%= alert %></p>
  </div>

    <%= yield %>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<!-- views/recipe_foods/edit.html.erb -->

<div class="container w-75">
  <h1 class="text-center">Modify Ingredient in <%= @recipe.name %></h1>

  <%= form_with(model: [@recipe, @recipe_food], url: recipe_recipe_food_path(@recipe, @recipe_food), method: :patch, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :food_id, 'Food' %>
      <%= form.collection_select(:food_id, Food.all, :id, :name, prompt: 'Select a food', class: 'form-control') %>
    </div>
    <div class="mb-3">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, class: 'form-control', required: true %>
    </div>

    <div class="d-flex justify-content-center">
      <%= form.submit 'Modify Ingredient', class: 'btn btn-sm btn-outline-success w-100' %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<!-- views/recipe_foods/new.html.erb -->

<div class="container w-75">
  <h1 class="text-center">Add Ingredient to <%= @recipe.name %></h1>

  <%= form_with(model: [@recipe, @recipe.recipe_foods.build], url: recipe_recipe_foods_path(@recipe), local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :food_id, 'Food' %>
      <%= form.collection_select(:food_id, Food.all, :id, :name, prompt: 'Select a food', class: 'form-control') %>
    </div>
    <div class="mb-3">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, class: 'form-control', required: true %>
    </div>

    <div class="d-flex justify-content-center">
      <%= form.submit 'Add Ingredient', class: 'btn btn-outline-success w-100' %>
    </div>
  <% end %>
</div>

app/views/recipes/add_ingredient.html.erb
<!-- views/recipes/add_ingredient.html.erb -->

<div class="container">
  <h1 class="text-center">Add Ingredient to <%= @recipe.name %></h1>

  <%= form_with(model: [recipe, recipe.foods.build], url: recipe_foods_path(recipe), local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :food_id, 'Food' %>
      <%= form.collection_select(:food_id, Food.all, :id, :name, prompt: 'Select a food', class: 'form-control') %>
    </div>
    <div class="mb-3">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, class: 'form-control', required: true %>
    </div>
    <!-- Other fields as needed -->
    <%= form.submit 'Add Ingredient', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<!-- views/recipes/index.html.erb -->

<div class="container d-flex flex-column gap-4">
  <h1 class="text-center">Public Recipes</h1>
  <!-- Add the button at the top right corner -->
  <div class="d-flex justify-content-end pe-5">
    <%= button_to "Add Recipe", new_recipe_path, method: :get, class: "btn btn-sm btn-outline-secondary" %>
  </div>

  <% @recipes.each do |recipe| %>
    <div class="row" style="border-style: solid;">
      <div class="col-md-4">
        <%= link_to recipe_path(recipe) do %>
        <h3><%= recipe.name %></h3>
        <% end %>
        <h5>By <%= recipe.user.name %></h5>
      </div>
      <div class="col-md-4">
        <h5>Total food items: <%= recipe.foods.count %></h5>
        <h5>Total price: $<%= recipe.recipes_total_price %></h5>
      </div>
      <div class="col-md-4 d-flex justify-content-end align-self-center">
        <!-- Display Delete button only for recipes created by the current user -->
        <% if current_user && current_user.id == recipe.user.id %>
          <%= button_to "Delete", recipe_path(recipe), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/my_recipes.html.erb
<!-- views/recipes/my_recipes.html.erb -->

<div class="container d-flex flex-column gap-4">
  <h1 class="text-center">My Recipes</h1>
  <% @recipes.each do |recipe| %>
    <div class="row" style="border-style: solid;">
      <div class="col-md-6 d-flex flex-column justify-content-between">
        <%= link_to recipe_path(recipe) do %>
        <h3><%= recipe.name %></h3>
        <% end %>
        <!-- Add the "REMOVE" button with a link to delete the recipe -->
        <%= link_to 'REMOVE', recipe_path(recipe), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger w-25 mb-1' %>
      </div>
      <div class="col-md-6">
        <p><strong><%= recipe.description %></strong></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<!-- views/recipes/new.html.erb -->

<div class="container w-75">
  <h1>Add New Recipe</h1>

  <%= form_with model: @recipe, url: recipes_path, include_hidden: false do |form| %>
    <% if @recipe.errors.any? %>
      <div>
        <h2><%= pluralize(@recipe.errors.count, "error") %> Recipe cannot be saved:</h2>
        <ul>
          <% @recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-flex flex-column">
      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name, class: 'form-control', required: true %>
      </div>
      <div>
        <%= form.label :preparation_time %><br>
        <%= form.number_field :preparation_time, class: 'form-control', required: true %>
      </div>
      <div>
        <%= form.label :cooking_time %><br>
        <%= form.number_field :cooking_time, class: 'form-control', required: true %>
      </div>
      <div>
        <%= form.label :description %><br>
        <%= form.text_area :description, class: 'form-control', required: true %>
      </div>
      <div>
        <%= form.label :is_public? %><br>
        <%= form.check_box :is_public %>
      </div>
      <%= form.submit "Create Recipe", class: "btn btn-outline-success mt-3" %>
    </div>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<div class="container">
    <h1 class="text-center">Shopping List</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h5>Amount of food items to buy: <%= @recipe.recipe_foods.count %></h5>
        </div>
        <div class="col-md-6 d-flex">
            <h5>Total value of food needed: $<%= @recipe.recipes_total_price %></h5>
        </div>
    </div>
</div>
<hr />
<div class="container table-responsive">
    <table class="table table-striped table-hover table-sm table-bordered">
        <thead>
            <tr>
                <th>Food</th>
                <th>Quantity</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <% @recipe.recipe_foods.each do |recipe_food| %>
                <tr>
                    <td><%= recipe_food.food.name %></td>
                    <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
                    <td>$<%= recipe_food.value %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/recipes/show.html.erb
<!-- views/recipes/show.html.erb -->

<div class="container">
  <h1 class="text-center"><%= @recipe.name %></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4>Preparation time: <%= @recipe.preparation_time %> hours</h4>
      <h4>Cooking time: <%= @recipe.cooking_time %> hours</h4>
    </div>
    <div class="col-md-6 d-flex justify-content-end align-items-center">
      <label class="form-label fs-3 me-3 fw-bold mt-2">
        Is Public
      </label>
      <% if @recipe.user == current_user %>
      <%= form_with(model: @recipe, url: recipe_path(@recipe), method: :patch) do |form| %>
        <div class="form-check fs-3">
          <%= form.check_box :is_public, class: 'form-check-input', onchange: 'this.form.submit()' %>
        </div>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h4>Description</h4>
      <p><%= @recipe.description %></p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <%= link_to 'Generate Shopping List', shopping_list_recipe_path(@recipe), class: 'btn  btn-sm btn-secondary' %>
    </div>
    <% if @recipe.user == current_user %>
      <div class="col-md-6 d-flex justify-content-end">
        <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn  btn-sm btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

<hr />
<!-- views/recipes/show.html.erb -->

<div class="container table-responsive">
  <table class="table table-striped table-hover table-sm table-bordered">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.value %></td>
          <td class="d-flex justify-content-between">
            <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food) %>
            <%= link_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shopping_list/general.html.erb
<!-- app/views/shopping_list/general.html.erb -->

<div class="container">
  <h1 class="text-center">General Shopping List</h1>
  <h5>Amount of food items to buy: <%= @total_items %></h5>
  <h5>Total value of food needed:  <%= @general_total_price %></h5>

  <table class="table table-striped table-hover table-sm table-bordered">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
  <% @missing_foods.each do |deficit_item| %>
    <tr>
      <td><%= deficit_item[:food].name %></td>
      <td><%= deficit_item[:deficit_quantity] %> <%= deficit_item[:food].measurement_unit %></td>
      <td>$<%= deficit_item[:food].price %></td>
    </tr>
  <% end %>
</tbody>
  </table>
</div>